default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ilibrary_dev

test:
  <<: *default
  database: ilibrary_test

production:
  <<: *default
  database: ilibrary_production
  username: BookLibrary
  password: <%= ENV['BOOKLIBRARY_DATABASE_PASSWORD'] %>
